# Generated by Django 4.2.19 on 2025-02-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_number', models.CharField(max_length=5)),
                ('lecture_time', models.TextField(blank=True, null=True)),
                ('hw_dates', models.TextField(blank=True, null=True)),
                ('exam_dates', models.TextField(blank=True, null=True)),
                ('late_day', models.CharField(max_length=10)),
                ('attendance', models.TextField(blank=True, null=True)),
                ('grade_weight', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
