# Generated by Django 4.2.19 on 2025-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan4me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='fce',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
